apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  title: Platform Engineering
  description: The team responsible for the internal platform
spec:
  type: team
  children: []
