apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: workday.time.approve
  title: Approve Time Off
  description: ""
  tags:
    - write
    - time-off
    - manager-only
  annotations:
    capability-api/domain: workday.time
    capability-api/sensitivity: high
    capability-api/requires-mfa: "false"
    capability-api/governed-by: admin-full-access, hr-staff-time-management, local-dev-extended-access, manager-time-approval
  links:
    - title: Policy Verification
      url: http://localhost:3000/docs/default/component/capability-api/governance
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: platform-engineering
  system: workday-time
  definition: |
    openapi: 3.0.0
    info:
      title: Approve Time Off
      description: 
      version: 1.0.0
    paths:
      /{action}:
        post:
          summary: Approve Time Off
          operationId: workday_time_approve
          tags:
            - write
            - time-off
            - manager-only
          responses:
            '200':
              description: Successful operation