apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: workday.time.get_balance
  title: Get PTO Balance
  description: 
  tags:
    - read-only
    - time-off
  annotations:
    capability-api/domain: workday.time
    capability-api/sensitivity: low
    capability-api/requires-mfa: "false"
    capability-api/governed-by: admin-full-access, ai-analyst-time-read, ai-assistant-time-read, employee-time-self-service, hr-staff-time-management, local-dev-extended-access, manager-time-approval, reporting-service-time-read
  links:
    - title: Policy Verification
      url: /docs/default/component/capability-api/governance
      icon: dashboard
spec:
  type: action
  lifecycle: production
  owner: platform-engineering
  system: workday-time
  definition: |
    # Get PTO Balance
    
    
    
